/**
 * ============================================================================
 * HTTP WRAPPERS -- the single funnel every route goes through
 * ============================================================================
 *
 * These are the server-side twins of `window.runMutation` / `window.runQuery`
 * in `SRC/src/JS_State.html`. The original grew those two funnels for the
 * reason recorded in AUDIT_2026-08-24.md A1/A2: every call site was doing its
 * own ad-hoc error handling, most of them badly, and the two error returns the
 * server actually produces -- "Row data mismatch. The sheet may have been
 * modified." and "Server busy. Please try again." -- were being discarded on
 * the way to the operator, who then saw the drawer repaint the OLD number and
 * tapped again.
 *
 * The HTTP layer is a second place that error string has to survive. A route
 * that catches a `{success:false}` and answers `200 {...}`, or answers
 * `500 "Internal Server Error"`, destroys it just as thoroughly as the old
 * bare `.withSuccessHandler()` did. So: one wrapper, applied to every route,
 * with the rules below.
 *
 * THE CONTRACT
 * ------------
 * 1. `context` is the Express `req`, passed straight into the service. That is
 *    what `getActiveUserEmail(context)` reads (functions/auth.js), so every
 *    Audit_Log row written under a route is attributed to the signed-in
 *    operator rather than to a placeholder.
 *
 * 2. A service that returns `{success:false}` produces a NON-2XX carrying the
 *    service's own text verbatim. Both spellings are honoured: Service_Write /
 *    Service_Assembly / Service_Dates / Service_Diagnostics return
 *    `{success:false, error}`, while Service_Read and Service_PO_Ingest return
 *    `{success:false, message}`. A wrapper that only knew about `error` would
 *    turn all 57 of Read's refusals into an empty string.
 *
 * 3. A service-level refusal is never a 200, and never a generic 500. It is a
 *    422: the request was well-formed and authenticated, and the service
 *    declined it for a business reason it has already explained. 500 is
 *    reserved for a genuine thrown exception, which is a different thing and
 *    should be findable as such in the logs.
 *
 * 4. A mutation that resolves to `undefined`/`null` is a FAILURE, not a
 *    success. That is AUDIT A1 exactly -- `modifySheetRow` used to fall off the
 *    end returning nothing while the caller answered `{success:true}`. Phase 1
 *    fixed the service; this makes the same mistake impossible to reintroduce
 *    from the route layer.
 *
 * 5. The whole result object is echoed alongside `success:false`, so partial
 *    outcomes survive -- `receivePOCardItems`' `trelloSynced:false` +
 *    `failedItems[]`, `findOrCreatePOCardAndInject`' s `requiresManualReview`.
 *    Only the `error` key is normalised.
 */

const logger = require('firebase-functions/logger');

/** Non-2xx used for a service-level refusal. See rule 3 above. */
const REFUSED_STATUS = 422;

/**
 * Pull the human-readable failure text out of a service result, honouring both
 * spellings in use across the services.
 *
 * @param {Object} result a service return value with success === false.
 * @return {string} the service's own error text, never empty.
 */
function failureText(result) {
  const text = result && (result.error || result.message);
  const trimmed = String(text === undefined || text === null ? '' : text).trim();
  // An empty string here means a service returned `{success:false}` with no
  // explanation at all. Say so rather than sending a blank error, which reads
  // to the operator as "it worked but nothing happened".
  return trimmed || 'The server refused the request but gave no reason. Check the function logs.';
}

/**
 * Shared response path for both wrappers.
 *
 * @param {string} kind 'read' | 'mutation'.
 * @param {string} name route label, for logs.
 * @param {Function} handler async (req) => service result.
 * @return {Function} an Express handler.
 */
function runRoute(kind, name, handler) {
  return async function routeHandler(req, res) {
    // Lets the SPA (and anything reading a HAR) tell a read apart from a write
    // without parsing the path, and keeps the distinction visible in logs.
    res.set('X-CIS-Route-Kind', kind);

    let result;
    try {
      result = await handler(req);
    } catch (e) {
      // A throw is an unhandled fault, not a business refusal -- 500, and the
      // message goes to the client rather than being flattened into
      // "Internal Server Error". Every one of these strings is generated by
      // our own code or the Sheets/Trello client; none of it is user data.
      logger.error(kind + ' route threw: ' + name, {
        error: e.message,
        stack: e.stack,
        operator: (req.auth && req.auth.email) || null
      });
      return res.status(500).json({
        success: false,
        error: name + ' failed: ' + e.message
      });
    }

    // Rule 4. Reads are held to the same standard: a read that resolves to
    // nothing has failed, and answering `200 null` just moves the confusion
    // into the render layer.
    if (result === undefined || result === null) {
      logger.error(kind + ' route returned no result: ' + name, {
        operator: (req.auth && req.auth.email) || null
      });
      return res.status(500).json({
        success: false,
        error: name + ' returned no result. Nothing was ' +
          (kind === 'mutation' ? 'written' : 'read') + '; this is a server bug, not a rejected request.'
      });
    }

    // Rule 2/3/5.
    if (result.success === false) {
      const error = failureText(result);
      logger.warn(kind + ' route refused: ' + name, {
        error,
        operator: (req.auth && req.auth.email) || null
      });
      return res.status(REFUSED_STATUS).json(Object.assign({}, result, {
        success: false,
        error
      }));
    }

    return res.status(200).json(result);
  };
}

/**
 * Wrap a mutation. `handler` receives the Express `req` and must pass it on to
 * the service as its `context` argument so Audit_Log attribution works.
 *
 *   router.post('/inventory/set-total', runMutation('Set total stock', (req) =>
 *     Service_Write.setTotalStock(req.body.locId, req.body.sku, req.body.newQty,
 *                                 req.body.instanceOrRowId, req)));
 *
 * @param {string} name route label, used in error text and logs.
 * @param {Function} handler async (req) => service result.
 * @return {Function} an Express handler.
 */
function runMutation(name, handler) {
  return runRoute('mutation', name, handler);
}

/**
 * Wrap a read. Same failure rules -- several reads (`getTrelloLists`,
 * `getExistingCardChecklist`, `getCardShippingReference`, …) also return
 * `{success:false, message}`, and those must not arrive as a 200 either.
 *
 * @param {string} name route label, used in error text and logs.
 * @param {Function} handler async (req) => service result.
 * @return {Function} an Express handler.
 */
function runQuery(name, handler) {
  return runRoute('read', name, handler);
}

/**
 * A route for a server call the SPA makes that is NOT yet ported. Answers 501
 * naming the original file and what it is waiting on.
 *
 * Deliberately a real route and not a 404: a 404 is indistinguishable from a
 * typo in the path, which sends whoever hits it looking in the wrong place. A
 * 501 that names `Fedex_Master_Script.js` is a finished answer.
 *
 * @param {string} name the original Apps Script function name.
 * @param {string} waitingOn what has to land first.
 * @return {Function} an Express handler.
 */
function notImplemented(name, waitingOn) {
  return function notImplementedHandler(req, res) {
    res.set('X-CIS-Route-Kind', 'unimplemented');
    return res.status(501).json({
      success: false,
      error: name + '() is not ported yet. Waiting on: ' + waitingOn + '.',
      notImplemented: true,
      originalFunction: name,
      waitingOn
    });
  };
}

module.exports = {
  REFUSED_STATUS,
  failureText,
  runMutation,
  runQuery,
  notImplemented
};
